version: '3.5'

networks: 
  net-backend:
    driver: bridge


services:
  
  oracle-db:
    
    image: oracleinanutshell/oracle-xe-11g:latest
    restart: always
    
    environment:
      - ORACLE_ALLOW_REMOTE=true

    ports:
      - 8080:8080
      - 1521:1521
      - 5500:5500
    
    networks:
      - net-backend

    volumes:
       - ${PWD}\oracle\data:/u01/app/oracle/oradata/oracle11g-data/
       - ${PWD}\oracle\init/sh_sql_dmp_files:/docker-entrypoint-initdb.d/
       #- ${PWD}/oracle/data:/u01/app/oracle/oradata/oracle11g-data/
       #- ${PWD}/oracle/init/sh_sql_dmp_files:/docker-entrypoint-initdb.d/
       

